# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=200)),
                ('exam_room', models.IntegerField()),
            ],
        ),
    ]
