# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_auto_20190221_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
    ]
