# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0004_appointment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
