# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0005_auto_20190221_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_doctor_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_doctor_started',
            field=models.DateTimeField(null=True),
        ),
    ]
