# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0006_auto_20190221_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_patient_checkedin',
            field=models.DateTimeField(null=True),
        ),
    ]
