# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0007_appointment_time_patient_checkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time_patient_checkedin',
            new_name='time_checkedin',
        ),
    ]
