# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0008_auto_20190221_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_patient_waited',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
