# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0009_appointment_time_patient_waited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_patient_waited',
            field=models.DateTimeField(null=True),
        ),
    ]
