# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0010_auto_20190221_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_patient_waited',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
