# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0011_auto_20190221_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
