# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0012_auto_20190226_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
